export const TableFields = [
    {name: 'Company', hidden: false, width: 'lg', id: 'company',},
    {name: 'Name', hidden: false, width: 'lg', id: 'name',},
    {name: 'Additional', hidden: false, width: 'lg', id: 'additional',},
    {name: 'Street', hidden: false, width: 'md', id: 'street',},
    {name: 'Postal Code', hidden: false, width:'md', id: 'postal',},
    {name: 'Country', hidden: false, width:'md', id: 'country',},
    {name: 'IBAN', hidden: false, width:'md', id: 'IBAN',},
    {name: 'BIC', hidden: false, width:'md', id: 'BIC',},
    {name: 'Bank Name', hidden: false, width:'sm', id: 'bank',},
    {name: 'Fax', hidden: false, width:'md', id: 'fax',},
    {name: 'Email', hidden: false, width:'sm', id: 'email',},
    {name: 'Birthday', hidden: false, width:'lg', id: 'birthday',},
    {name: 'Homepage', hidden: true, width:'', id: 'homepage',},
]