export const dummyPeople = [
  {
    id: "1",
    company: "Facebook",
    name: "John Smith",
    additional: "Has a cat",
    street: "Test Street 123",
    postal: "12345",
    country: "Ukraine",
    IBAN: "123456789",
    BIC: "65432",
    bank: "PrivatBank",
    fax: 9087653,
    email: "test@test.com",
    birthday: String(new Date().getDay()),
    homepage: "",
  },
  {
    id: "2",
    company: "Amazon",
    name: "Sarah Smith",
    additional: "Has a cat",
    street: "Test Street 123",
    postal: "12345",
    country: "Ukraine",
    IBAN: "987654321",
    BIC: "6453756",
    bank: "PrivatBank",
    fax: "",
    email: "test@test.com",
    birthday: String(new Date().getDay()),
    homepage: "",
  },
];
